### ISSUE TITLE
Adding Support for Custom Dimensions and Metrics

### ISSUE THREAD

**Issue by okcompewter** [angulartics/angulartics-google-analytics#10]
I noticed the support for adding custom dimensions or metrics is missing.

Google Analytics allows setting them like this:

`ga('set', 'dimension1', 'Level 1');` [(documentation)](https://support.google.com/analytics/answer/2709828?hl=en#example-session-collection)

or 

`ga('set', 'metric1', 1 );` [(documentation)](https://support.google.com/analytics/answer/2709828?hl=en#example-metrics-collection)

So being able to use something like this format:

`$analytics.setDimensionMetric('dimension1', 'Level 1');`

or

`$analytics.setDimensionMetric('metric1', 1);`

Looking at the code, it would probably just need a new register like this:

    $analyticsProvider.registerSetDimensionMetric(function (index, value) {
    ...
    })

Hopefully you can get this in. Thanks!

**Comment by aparij** [comment]
I think this PR : #9  is solving your problem

**Comment by timelf123** [comment]
This is done, thanks for the suggestion!
