### ISSUE TITLE
Events tracking not working with UserID

### ISSUE THREAD

**Issue by DamodarSojka** [angulartics/angulartics-google-analytics#103]
To be honest I am not entirely sure that's a problem with this plugin or with angulartics.

No events are being shown in the google analytics dashboard when UserID feature is enabled. The events are tracked without the UserID feature and the navigation is working with both UserID and without it.

If you feel like that's not the bug with this plugin or with angulartics I would appreciate any help or hint on where to ask further or what the cause could be.
Cheers

**Comment by DanWilkerson** [comment]
If this is still an issue, share your configuration and I'll take a look.
