### ISSUE TITLE
Autolinker & Full path tracking

### ISSUE THREAD

**Issue by bo25tbird** [angulartics/angulartics-google-analytics#104]
I have my Angular JS app on a subdomain, so am using the Google Anaytics autoLink between domain.com & app.domain.com.  The issue is it appends the beginning of my angular JS path.  I'm using full path tracking and so might be trying to pick up the ?_gs=123 as a page or ignoring it completely from the ?_
Any idea on a fix?

https://app.smith.com/?_ga=2.123423528.72087221.1494478657-1323090092.1483945723#!/search/smith/global/no-stateall-types-of-smiths/all-industries/no-specifics-searched/

script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-82342344-1', { '**cookieDomain': 'none' });
  ga('require', 'linker');
  ga('linker:autoLink', ['smith.com', 'app.smith.com']);**
</script>

**Comment by DanWilkerson** [comment]
You don't need to use cross domain tracking and your cookieDomain setting is incorrect. Set cookieDomain to 'auto' and remove the require and linker statements - as long as you're using the same Property ID to track both subdomains, your users will be correctly tracked. You may wish to modify your referral exclusion list as well. Here's a complete blog post on how to do what I'm talking about:

http://www.lunametrics.com/blog/2016/08/11/subdomain-tracking-google-analytics/
