### ISSUE TITLE
improve request  : Google Single page application recommandations

### ISSUE THREAD

**Issue by Benraay** [angulartics/angulartics-google-analytics#107]
I found this page on google analytics documentation : 
https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications

It says we should set the page and then call a pageview Event like this : 
ga('set', 'page', '/new-page.html');
ga('send', 'pageview');

and not putting the "page" parameter on the "pageview" Event because other
calls like Events would be attached to the old page

Benjamin Raaymakers

--edited by @timelf123 to reflect OP's original post from another issue)

**Comment by DanWilkerson** [comment]
Hi Benjamin,

This is covered by the current codebase; thank you for sharing your finding.

Dan
