### ISSUE TITLE
'google-analytics' string in filename causes plugin to be filtered by various browser privacy exensions 

### ISSUE THREAD

**Issue by jmcmichael** [angulartics/angulartics-google-analytics#13]
At least one Chrome privacy extension, uBlock origin, blocks any URL containing the string 'google-analytics', and I imagine other extensions do as well, since that is the name of the google analytics server domain.

You may want to consider a name change as this can be a frustrating problem to troubleshoot, and if developers aren't concatenating/uglifying their applications, total app failure for users who have privacy extensions installed.

**Comment by elmalto** [comment]
Same issue here

**Comment by timelf123** [comment]
Thanks for reporting. Any ideas for an alternative name?

**Comment by toksea** [comment]
Same issue has discussed here: https://github.com/angulartics/angulartics/issues/58

`angulartics-ga.js` is recommeded.

**Comment by timelf123** [comment]
Good catch @toksea I forgot we had already discussed this :P

**Comment by Emeegeemee** [comment]
Disregard that pull request picked the wrong issue.

**Comment by timlevett** [comment]
Based on comment from @toksea , I went ahead and did the change in #34.
