### ISSUE TITLE
Unable to get setUsername to work 

### ISSUE THREAD

**Issue by yaronguez** [angulartics/angulartics-google-analytics#14]
Hi there, I'm calling $analytics.setUsername('<USERNAME>') in my code but it doesn't seem to work.  While the session shows up in the Real-Time overview of my default view, it doesn't show up in the Real-Time overview of my User ID view and is thus not recognized by GA as having a Username set.  

When I set Usernames from a non-angular website using ga('set', '&uid', '<USERNAME>'); the session does indeed show up in the Real-Time overview of the User ID view so I know the view is configured correctly.

Any help is much appreciated, thanks!

**Comment by yaronguez** [comment]
Moving the setUsername to a different part of my application, within a watch event, resolved the issue for some reason.  Odd.

**Comment by DanWilkerson** [comment]
Hm, I'll take a look.

**Comment by twall** [comment]
I'm having a similar issue.  It'd be handy to know at what point it's safe to make the `setUsername()` call.  The google analytics debug plugin for chrome claims there's already a "ga" object in existence, which may be part of the problem.

**Comment by timelf123** [comment]
Where are you calling setUsername @twall

**Comment by twall** [comment]
I have an app.factory which returns a number of functions, one of which is an “authenticate” function, e.g.

app.factory(‘Auth’, [‘$q’, ‘$analytics’, …, function($q, $analytics, …) {
    return {
        authenticate: function () {
            var deferred = $q.defer();
            Accounts.get(function(account) {
                $analytics.setUsername(account.user_id.toString());
                $analytics.setUserProperties({‘dimension1’: account.org_id.toString());
            }, function(error) {
                // ...
            });
        }        
}]);

I’m not entirely sure of the context where this factory gets used (I’m a bit green with angular, and don’t normally visit this code).
