### ISSUE TITLE
Unable to set username

### ISSUE THREAD

**Issue by thandaanda** [angulartics/angulartics-google-analytics#18]
I am using this code to set username for Google Analytics and Mixpanel. Mixpanel works, but GA doesnt

```javascript
$analytics.setUserProperties({
	"id": sub.id,
	"email": sub.email,
	"name": userData.firstName + ' ' + userData.lastName
});
$analytics.setUsername(sub.id);
````

**Comment by timelf123** [comment]
Can you try the solution from https://github.com/angulartics/angulartics-google-analytics/issues/14

moving the setUsername to a watch - and let us know how it goes?

**Comment by thandaanda** [comment]
Code worked perfectly. Maybe I was seeing old report. Thanks!!
