### ISSUE TITLE
What do you think about adding support for beacons?

### ISSUE THREAD

**Issue by icfantv** [angulartics/angulartics-google-analytics#20]
Reading this:  http://stackoverflow.com/questions/30574526/google-analytics-xhr-instead-of-pixel-tracking, what do you guys think about modifying https://github.com/angulartics/angulartics-google-analytics/blob/master/lib/angulartics-google-analytics.js#L96 and allowing for the user to be able to specify whether or not to use beacons?

Is this worth pursuing?

**Comment by timelf123** [comment]
It looks easy enough. I can add a PR later this week unless someone beats
me to it

**Comment by icfantv** [comment]
Yea.  Think it's worth pursuing?
