### ISSUE TITLE
Reason not to require angulartics ^1.0.0 rather than ~1.0.0?

### ISSUE THREAD

**Issue by robations** [angulartics/angulartics-google-analytics#29]
Is there a reason to specify angulartics as a peer dep as `~1.0.0` rather than `^1.0.0`?

If you don't make breaking changes through 1.x then the caret should make for easier dependency management, in my experience. Take for example the scenario `X required ~1.1.1 but you have 1.2.3 installed`. Just a thought.

**Comment by timelf123** [comment]
Nope, just spaced out. I'll fix it for next release, thanks!

**Comment by robations** [comment]
Cool. I'll admit I have a post-it on my monitor explaining the difference between ~ and ^, because I always forget :)

**Comment by lazychino** [comment]
:+1: this is causing npm install to break with angulatics@1.1.0.

```
npm ERR! Linux 4.4.0-22-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package angulartics@1.1.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer angulartics-google-analytics@0.1.4 wants angulartics@~1.0.0
```

**Comment by Nexxado** [comment]
```
+-- UNMET PEER DEPENDENCY angulartics@1.1.0
`-- angulartics-google-analytics@0.1.4
```
i just got this, when i installed angulartics a moment before

**Comment by timelf123** [comment]
[0.2.0](https://github.com/angulartics/angulartics-google-analytics/releases/tag/0.2.0) released today, sorry for the wait.

https://github.com/angulartics/angulartics-google-analytics/blob/master/package.json#L48 closes this
