### ISSUE TITLE
eventTrack() Custom Dimensions are set on the Tracker and are therefore sent with every subsequent event.

### ISSUE THREAD

**Issue by northsoul70** [angulartics/angulartics-google-analytics#37]
A change was made in [9898229](https://github.com/angulartics/angulartics-google-analytics/commit/9898229e9fa203e511aec5aaa62c06d8b48ba961) which sets each custom dimension/metric on the Tracker:

`ga('set', 'dimension' + idx.toString(), properties['dimension' + idx.toString()]);`

This causes every subsequent event to also contain those custom dimensions/metrics (even if they are set up as 'hit' scope).  Previously **'send'** had been used rather than **'set'**.  
This seems like the wrong default behavior for the eventTrack() function.

**Comment by timelf123** [comment]
What is the desired behavior here? I'm happy to review a PR.

Change set to send?

**Comment by DanWilkerson** [comment]
@timelf123 CD's should passed as an object to the send command when the event fires. I'm hoping to put a PR on this Saturday or Sunday.

**Comment by timelf123** [comment]
Thanks @northsoul70 for catching this bug and in advance to @DanWilkerson for fixing it!

**Comment by DanWilkerson** [comment]
@timelf123  yup, on it

**Comment by DanWilkerson** [comment]
This was fixed with #38
