### ISSUE TITLE
Unable to Unset a Custom Dimension / Metric

### ISSUE THREAD

**Issue by IdanCo** [angulartics/angulartics-google-analytics#41]
The current implementation of custom dimension/metric does not allow to unset them.

When dealing with a single page applications, setting custom dimensions must be revertible, because they are persistent by design, meaning each ga call made after setting them will continue to pass the same dimensions.

to unset a value, you must pass a null value ([as explained here](http://stackoverflow.com/questions/35177932/how-can-i-clear-unset-custom-dimensions-from-google-analytics))

But the current implementation includes a condition that will not be truthy if the dimension value is null:
`if (properties['dimension' +idx.toString()]) {`

I will soon create a pull request with a possible fix.

**Comment by DanWilkerson** [comment]
Fixed by #38!
