### ISSUE TITLE
Improvements to the Dimension / Metric handling

### ISSUE THREAD

**Issue by IdanCo** [angulartics/angulartics-google-analytics#43]
Following #41 & #42 , i did a little test to find the best way to iterate over the properties -
https://jsfiddle.net/qvLokkou/

Apparently the current implementation is 10x slower than the other method.

I'll create a pull request soon, but since we're talking about a few milliseconds here or there, don't hold your breath :-)

**Comment by DanWilkerson** [comment]
>   lastthing: 'yolo'

:laughing:

Awesome, I'll let you know if we snag this in another PR before then :+1: Thanks again for contributing!
