### ISSUE TITLE
angulartics.google.tagmanager is not available

### ISSUE THREAD

**Issue by tsanne** [angulartics/angulartics-google-analytics#45]
I am trying to integrate angulartics with our angularjs app.  I am new to angularjs, so hopefully I'm not doing something stupid.

In our app.js file, I added the two modules for angulartics and google tag manager:

    app = root.app = angular.module("CustomerCenterApp", ["ngRoute", "ui.bootstrap", "ngSanitize", "ngAnimate", "mgcrea.ngStrap", "ngIdle",
         "Config", "Logging", "clientBrandingModule", "angulartics", "angulartics.google.tagmanager"]);

	In our index.html, after the other angular script files, I added:
	
	<script src="assets/lib/angular/angulartics_1.0.2/angulartics.min.js"</script>
	<script src="assets/lib/angular/angulartics_1.0.2/angulartics-gtm.min.js"</script>

I uploaded these scripts to our lib directory in the location referenced above

But when I try to load the site, I get:
		
Uncaught Error: [$injector:modulerr] Failed to instantiate module CustomerCenterApp due to:
Error: [$injector:modulerr] Failed to instantiate module angulartics.google.tagmanager due to:
Error: [$injector:nomod] Module 'angulartics.google.tagmanager' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.2.27/$injector/nomod?p0=angulartics.google.tagmanager

I appreciate any ideas...

**Comment by DanWilkerson** [comment]
Hi Tsanne!

This is a little off-topic for our issues; we don't really do this kind of support/debugging. That said, I'm happy to help you get this ironed out via PM - could you ping me directly either here or at notdanwilkerson@gmail.com? Thanks!

Dan
