### ISSUE TITLE
additional trackers (additionalAccountNames) not used by setUserProperties

### ISSUE THREAD

**Issue by ddcovery** [angulartics/angulartics-google-analytics#46]
setUserProperties sends custom dimensions/metrics to the default tracker, not the additional ones configured by additionalAccountNames

**Comment by aditcmarix** [comment]
Can any one working on this issue..?

**Comment by DanWilkerson** [comment]
This shouldn't be too hard to do. I'll add in a configuration for this and pull it in.

**Comment by aditcmarix** [comment]
Thanks man to add this.
