### ISSUE TITLE
Change noninteraction on trackEvent method to nonInteracion

### ISSUE THREAD

**Issue by altsanz** [angulartics/angulartics-google-analytics#49]
I had to search on the source code why this

```
  $analytics.eventTrack('Signup', {
    category: 'Signup',
    action: 'Start signup',
    label: 'Start signup',
    nonInteraction: true
    })
```

was returning nonInteraction undefined, and it's because angulartics-google-analytics uses noninteraction, instead the same word as official google analytics functionality

This is counter-intuitive and it would be great to change it, I can do a PR with that.

Thanks for the good job anyways.

**Comment by zwacky** [comment]
thanks for pointing this out. i also ran into this **several times**.
i'd go for a solution that accepts both, `nonInteraction` and `noninteraction` for not breaking older projects.
