### ISSUE TITLE
How to prevent sending pageView hit

### ISSUE THREAD

**Issue by maliknur** [angulartics/angulartics-google-analytics#52]
I have deleted this line on main GA script 
`ga('send', 'pageview'); `
and want to send custom pageView with custom page url and title only when I needed it.
However it sends automatically pageView event when any page loads.

Moreover can bower.json include dist/angulartics-ga.min.js as main file rather than unminified version?
Otherwise we need to override bower settings.

**Comment by timelf123** [comment]
Check out this comment
https://github.com/angulartics/angulartics/issues/112#issuecomment-54228329

**Comment by maliknur** [comment]
Thanks, this is exactly what I'm looking for.
