### ISSUE TITLE
Hybrid Apps : screenview vs pageview

### ISSUE THREAD

**Issue by vsridhars** [angulartics/angulartics-google-analytics#57]
Hi,

I have a hybrid app. When I am testing on localhost with a GA web tracker and a sample angular project, I am seeing page views and events reach my GA Dashboard. VirtualPageViews is enabled. 

However, I have a hybrid app and hence would have to integrate with a GA app tracker. Once I do that, only the first page view reaches GA. Events reach GA. This is consistent with the SPA behaviour. 

When I go thru the angulartics-ga js code, I do not find any references to ga:send:screenview. Is that mode supported by Angulartics?

**Comment by DanWilkerson** [comment]
You want to use a Web profile for a hybrid app, not the "app" tracking. The App SDKs are meant to work with fully-native apps. If you're using cordova, we have a plugin available for that:

https://github.com/angulartics/angulartics-google-tag-manager-cordova

Angulartics doesn't work with App views.
