### ISSUE TITLE
Can I use Angular Expressions inside the directive attributes?

### ISSUE THREAD

**Issue by GonzaloShopear** [angulartics/angulartics-google-analytics#65]
I was wondering if I can, by example, write the next directive:

`<button angular-on="click" angular-event="{{event.type}}"></button>`

**Comment by akman003** [comment]
I can confirm that tracking works properly when using interpolation with an inferred analytics-event, e.g.

```
<button analytics-on="click" analytics-category="Buttons">{{ buttonLabel }}</button>
```

The contents of buttonLabel are getting tracked correctly.
