### ISSUE TITLE
How to set dynamic UA-xxxxxxxx-y code?

### ISSUE THREAD

**Issue by mrsinguyen** [angulartics/angulartics-google-analytics#7]
Currently, I don't know the way we can config the variable allow change GA Tracking ID.

Thanks

**Comment by timelf123** [comment]
Probably best to do this server side

**Comment by moravcik** [comment]
For SPA applications it is counterproductive to employ templating engine on server side for just setting dynamic variables. Although it looked promising, I am switching to another lib due to this problem.

**Comment by timelf123** [comment]
`$analyticsProvider.settings.ga.additionalAccountName = ['xxx'];`

**Comment by moravcik** [comment]
Thank you for the tip. However this undocumented feature does not seem like first-class support for this problem. I just need to initialize `angulartics-ga` **after** my `.config()`, where I run the GA snippet code with my resolved tracking ID from server.

**Comment by timelf123** [comment]
Can you describe your use case a bit more? It seems like what you are describing is -- do not allow `angulartics-ga` to run until your injected async script has loaded?

>just need to initialize angulartics-ga after my .config()

**Comment by moravcik** [comment]
It is close but not the same. I need to control the moment when `angulartics-ga` can grab `ga` and do the stuff. I have SPA application where the first thing I do is that I grab config from server and do the angularJS bootstrap afterwards. AKA, asynchronous bootstrap technique - described [here](https://blog.mariusschulz.com/2014/10/22/asynchronously-bootstrapping-angularjs-applications-with-server-side-data).

It's not that big deal, even if I had standard AngularJS setup I would like to have externalized tracker ID into constant. So at some point there is `.config()` function when I run the GA snippet (not in the `index.html`), where my gaTrackerID constant is injected and used. And just AFTER this I would need to allow `angulartics-ga` to do something with `ga` which is already present on window object.
