### ISSUE TITLE
Unenclosed ga triggering error

### ISSUE THREAD

**Issue by jasonbodily** [angulartics/angulartics-google-analytics#72]
The source code appears to include: 
  ```
$analyticsProvider.registerSetUserProperties(function (properties) {
    if(properties) {
      // add custom dimensions and metrics to each hit
      var dimsAndMets = dimensionsAndMetrics(properties);
      ga('set', dimsAndMets);
    }
  });
```
In all other places in the code, ga is enclosed with `if(window.ga) {}` however, here it is not. This throws an error if ga is not present.

**Comment by DanWilkerson** [comment]
This is fixed via https://github.com/angulartics/angulartics-google-analytics/pull/71 (will log "method not found" to console).
