### ISSUE TITLE
Google Analytics loaded asynchronously

### ISSUE THREAD

**Issue by rainerhahnekamp** [angulartics/angulartics-google-analytics#73]
Hello,

since I am loading ga.js asynchronously after angular's bootstraping is finished, I am receiving the exception:

`Error: neither Classic nor Universal Analytics detected at bootstrap. Angulartics-GA will ignore all commands!`

Is there some way to trigger the detection of the handler?

**Comment by DanWilkerson** [comment]
https://developers.google.com/analytics/devguides/collection/analyticsjs/#alternative_async_tracking_snippet

Can you put the first part (copied below) of the alternative snippet above Angulartics? 

```
<script>
window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
ga('create', 'UA-XXXXX-Y', 'auto');
ga('send', 'pageview');
</script>
```

If you're using Classic Analytics, you'll need to use this snippet instead:
```
<script>
  var _gaq = window._gaq = window._gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXX-X']);
  _gaq.push(['_trackPageview']);
</script>
```

**Comment by rainerhahnekamp** [comment]
Hi Dan,

thanks, that makes sense but I understood that I still have to remove the `ga('send', 'pageview')` line, right?

Greetings,
Rainer

**Comment by timelf123** [comment]
Correct, remove the `ga('send', 'pageview');` and let angulartics handle the pageviews

**Comment by rainerhahnekamp** [comment]
Understood :)
Thanks a lot

**Comment by kukac7** [comment]
it did not work with the async code, only the other.
if it was a `ga('send', 'pageview')`, you can run the pageview, but the page does not change when you do anything.

**Comment by kukac7** [comment]
🆙 😕

**Comment by timelf123** [comment]
@kukac7 I don't understand your issue

**Comment by kukac7** [comment]
@timelf123 I have a tracking does not work with the alternative snippet.

**Comment by DanWilkerson** [comment]
@kukac7 this is an exercise in redundancy, as the standard snippet forces Google Analytics to load asynchronously anyways - there's no reason to manually force an async load. You can use the standard snippet and you'll see the performance gains are moot, if any.

That said, please ensure the alternative snippet (everything but the `<script async src="..."></script>` tag are placed above the Angular files. Your code should look like this:

    <head>
        
       <script>
         window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
         ga('create', 'UA-XXXXX-Y', 'auto');
      </script>
    </head>
    <body>
      
       <script async src="...">
    </body>

**Comment by DanWilkerson** [comment]
Again, I want to stress that this is A) redundant and B) counterproductive to the purpose of adding Google Analytics to a website; users who browse away from the page before the snippet can load will not be tracked, which causes inconsistencies in reporting and undermines confidence in the data collected. The best practice recommendation is to always put the analytics snippet as high up in the <head> of your document as possible.
