### ISSUE TITLE
Module 'angulartics' is not available,You either misspelled the module name or forgot to load it

### ISSUE THREAD

**Issue by harshamadala** [angulartics/angulartics-google-analytics#84]
I am getting this error after following installation:
Module 'angulartics' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

My bower.json:
"dependencies": {
   "xxxx":"xxx",
    "angulartics-google-analytics":"~0.3.0"
  }

Ran bower install command and it created 	
        bower_components/angulartics-google-analytics/
	bower_components/angulartics/

In app.js
var testApp = angular.module("test", ['ui.router', 'oc.lazyLoad', 'ui.bootstrap', 'ngAnimate',
    'ngMessages', 'ui-notification', 'LocalStorageModule','angulartics', 'angulartics-google-analytics'
]);

Am I missing anything? And my angular js version 1.4.9.

Could you please help?

**Comment by timelf123** [comment]
You must include the path to angulartics.js in your script loader or index.html file with `<script>` tag
