### ISSUE TITLE
Account Id

### ISSUE THREAD

**Issue by steveharan** [angulartics/angulartics-google-analytics#85]
Where do you specify the GA account?  Thanks

**Comment by timelf123** [comment]
In your normal GA code invocation
` ga('create', 'UA-XXXXXXXX-X', 'none'); // 'none' while you are working on localhost`
or
` ga('create', 'UA-XXXXXXXX-X');`

**Comment by steveharan** [comment]
Just noticed that in your example, and it’s working.

Thanks a lot!

steve
