### ISSUE TITLE
Transport setting not working anymore

### ISSUE THREAD

**Issue by Frank3K** [angulartics/angulartics-google-analytics#87]
In commit aa0a779de8fd0b46463816e3d0b24511e102f9d2 (v0.3.0) the `transport` setting [got lost](https://github.com/angulartics/angulartics-google-analytics/commit/aa0a779de8fd0b46463816e3d0b24511e102f9d2#diff-965c9e0c5bdad19390d5dd9880a23abfL142). Now it's not working anymore.

Support for the `transport` setting was introduced in #21 and it is mentioned in the [readme](https://github.com/angulartics/angulartics-google-analytics/blob/a4d508dc0019c391a7b174364d208cfb0a289fc6/README.md#settings).

---

Reproduction: configure the `$analyticsProvider` as follows:

``` js
	.config(function($analyticsProvider) {
		$analyticsProvider.settings.ga.transport = 'beacon';
	});
```

Observe that image tracking is used using the developer tools.

**Comment by DanWilkerson** [comment]
Thanks for pointing this out, I've got a PR in that should fix the issue.
