### ISSUE TITLE
Can you use ga("set")?

### ISSUE THREAD

**Issue by otravers** [angulartics/angulartics-google-analytics#92]
This is a similar question to my earlier MixPanel issue (https://github.com/angulartics/angulartics-mixpanel/issues/26), I want to make sure this works the same with Google Analytics.

I want to use ga('set') to define custom dimensions, metrics, and content groups, can I just use the regular GA syntax via Angulartics? I.e. code like the following:

```
ga('set', {
  'dimension5': 'custom dimension data',
  'metric5': 'custom metric data'
});
```
and

`ga('set', 'contentGroup1', 'My Group Name'); `

**Comment by timelf123** [comment]
Yes
