### ISSUE TITLE
Missing method: registerTransactionTrack in Angulartics

### ISSUE THREAD

**Issue by Wuntenn** [angulartics/angulartics-google-analytics#93]
I'm getting an error:
`hint.js:569 Uncaught Error: [$injector:modulerr] Failed to instantiate module mean due to:`
>Error: [$injector:modulerr] Failed to instantiate module angulartics.google.analytics due to:
TypeError: $analyticsProvider.registerTransactionTrack is not a function
    at http://localhost:3000/lib/angulartics-google-analytics/lib/angulartics-ga.js:252:22

I've gone to the Angulartics code base and cannot find this method either. Has anyone else encountered this issue, or is anyone able to help?

**Comment by timelf123** [comment]
https://github.com/angulartics/angulartics/blob/master/src/angulartics.js#L59 do you have the latest angulartics?

**Comment by Wuntenn** [comment]
I decided to uninstall and re-install the modules just to be sure that issues weren't coming from inconsistent files. At that point I was using `Angulartics#1.3.0` and `Angulartics-google-analytics#0.4.0`

I've downgraded `Angulartics-google-analytics#0.4.0` to version  `Angulartics-google-analytics#0.3.0`and now i'm back to my [original issue :(](https://github.com/angulartics/angulartics/issues/533)

**Comment by Wuntenn** [comment]
Solved it... man i'm still dumb!

**Comment by ildikototh** [comment]
@Wuntenn  How did you solve this?
