### ISSUE TITLE
Support for social interactions?

### ISSUE THREAD

**Issue by otravers** [angulartics/angulartics-google-analytics#94]
Aside from pageviews and events, GA has a syntax specifically for "social interactions":
https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions

In GA code:
`ga('send', 'social', [socialNetwork], [socialAction], [socialTarget], [fieldsObject]);`

How is this supported by Angulartics? I search the doc and respository and couldn't find any mention of it.

**Comment by DanWilkerson** [comment]
We're really just a plugin for Angulartics, not so much a Google Analytics-specific lib. To that end, Angulartics doesn't have a trackSocial method (and I suspect that we probably won't, as it is GA specific AFAIK). 

As a consultant who works with Google Analytics every day, I'd recommend that you don't use the social interaction hit type at all, and instead use events and pass social data that way. That's what I do with all of my clients, the reason being that social interactions cannot be used for goals, and many of the Social reports have been sunset in recent months. Events provide the same data and functionality, and (handily) you can track them using the trackEvent method.

**Comment by otravers** [comment]
Thanks Dan for the quick reply and the good work you guys are doing at Luna. Up to now I've always used events for social tracking, for some reason I hadn't paid attention to the social interaction thing in GA. Bumped into it today while reviewing some documentation and I thought I might have missed something.
