### ISSUE TITLE
Is there a way to exclude specific events to be tracked.

### ISSUE THREAD

**Issue by surya1024** [angulartics/angulartics-google-analytics#98]
I am using angularities with multiple vendors and I like few of my events not be tracked by Google analytics, is there a way this can be achieved now?

**Comment by DanWilkerson** [comment]
No, and (although I don't speak for everyone), it seems very unlikely to me that this behavior would be supported.

**Comment by kwinz** [comment]
I would welcome this as a new feature.

There is a very real use case where you have different analytics vendors with some providing more in depth analytics (e.g. funnel analysis) while being more expensive or having different business model.
Some vendors charge much higher on a per event basis.

So a big+1 for this proposal from me. I would like to add a "blacklist" tag with a list of vendors that should not track this event to each declarative event.
